import { _electron as electron } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd();
const run=path.join(root,'artifacts','desktop-'+new Date().toISOString().replace(/[:.]/g,'-'));
await mkdir(run,{recursive:true});
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
let fixture, application;
const result={ok:false,checks:[],errors:[]};
const check=(name)=>{result.checks.push(name);console.log('PASS '+name);};
const launch=()=>electron.launch({args:[root],env:{...env,LIQUID_GLASS_USER_DATA:path.join(run,'user-data')},timeout:45000});
const waitFor=async(fn,message)=>{const end=Date.now()+45000;while(Date.now()<end){if(await fn())return;await new Promise(r=>setTimeout(r,200));}throw new Error(message);};
try {
 fixture=await electron.launch({args:[path.join(root,'scripts/fixture/main.cjs')],env:{...env,LIQUID_GLASS_FIXTURE_DATA:path.join(run,'fixture-data')},timeout:45000});
 const doc=await fixture.firstWindow(); await doc.waitForLoadState('load');
 application=await launch();
 const getMain=code=>application.evaluate(({app}, code)=>{ const _main=process.mainModule.require(app.getAppPath()+'/dist/main.cjs');return eval(code.replaceAll('main.', '_main.')); },code);
 await getMain('main.ready');
 const orb=application.windows().find(w=>w.url().includes('role=orb')) ?? await application.firstWindow();
 orb.on('pageerror',error=>result.errors.push(error.message));
 await orb.waitForSelector('.toolbar-grip',{state:'attached'});
 const telemetry=()=>getMain('main.appearance.telemetry()');
 await waitFor(async()=>{const t=await telemetry();return t?.liveTracks>0 && t.renderFrames>3;},'Real desktop capture did not become live');
 const first=await telemetry(); result.initial={tracks:first.liveTracks,gl:first.gl,video:[first.videoWidth,first.videoHeight],captureHz:first.captureHz,renderHz:first.renderHz};
 result.environment=await application.evaluate(({screen,app})=>({platform:process.platform,os:process.mainModule.require('node:os').release(),versions:process.versions,appPath:app.getAppPath(),displays:screen.getAllDisplays().map(d=>({bounds:d.bounds,scale:d.scaleFactor,rotation:d.rotation,refreshHz:d.displayFrequency,colorDepth:d.colorDepth,depthPerComponent:d.depthPerComponent}))}));
 check('independent startup and real getDisplayMedia desktop frames');
 assert.equal(await getMain("main.windows.get('orb').isContentProtected()"),true); check('material HWND content protection enabled');
 const shell=()=>orb.locator('.capsule-shell').boundingBox();
 const before=await shell();
 await doc.evaluate(()=>window.scrollTo(0,520));
 const frameBefore=(await telemetry()).captureFrames; await waitFor(async()=> (await telemetry()).captureFrames>frameBefore+3,'Capture stopped while scrolling');check('external document scroll while capture advances');
 const grip=await orb.locator('.toolbar-grip').boundingBox();
 await orb.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2); await orb.mouse.down(); await orb.mouse.move(grip.x+grip.width/2+100,grip.y+grip.height/2+70,{steps:20}); await orb.mouse.up();
 await waitFor(async()=>{const b=await shell();return b.x>before.x+50;},'Drag anchor did not move');check('capsule pointer drag commits anchor');
 await orb.getByRole('button',{name:'更多',exact:true}).click();
 await waitFor(async()=> (await telemetry()).menu?.open===true,'Menu did not render');
 await orb.waitForSelector('.liquid-menu[data-material=live]'); check('shared live menu opens');
 // Native foreground activation is not reliable from the automated inspector.
 // Exercise only the handler here; never report injected focus as native proof.
 result.nativeFocus='Native outside-window dismissal requires manual confirmation; handler tested with a test-only injected blur';
 await getMain("(() => { const w=main.windows.get('orb'), original=w.isFocused; w.isFocused=()=>false; w.emit('blur'); return new Promise(resolve=>setImmediate(()=>{w.isFocused=original;resolve();})); })()");
 await waitFor(async()=> (await telemetry()).menu?.open===false,'Blur handler did not dismiss menu'); check('blur handler closes menu (injected event; not native focus proof)');
 await orb.getByRole('button',{name:'更多',exact:true}).click(); await waitFor(async()=> (await telemetry()).menu?.open===true,'Reopen failed');
 await doc.evaluate(()=>window.scrollTo(0,0));
 await new Promise(resolve=>setTimeout(resolve,300));
 const bounds=await orb.locator('.liquid-menu').boundingBox(), cap=await shell();
 await orb.screenshot({path:path.join(run,'demo.png'),clip:{x:Math.max(0,Math.min(cap.x,bounds.x)-20),y:Math.max(0,cap.y-20),width:Math.max(cap.x+cap.width,bounds.x+bounds.width)-Math.min(cap.x,bounds.x)+40,height:bounds.y+bounds.height-cap.y+40},omitBackground:true});
 await orb.getByRole('button',{name:'收起更多',exact:true}).click();
 await waitFor(async()=> (await telemetry()).menu?.open===false,'Menu did not close'); check('menu closes without drawing stale layer');
 await orb.getByRole('button',{name:'提示脉冲',exact:true}).click();check('demo pulse callback');
 await getMain("main.act('appearance')");
 await waitFor(async()=>application.windows().some(w=>w.url().includes('role=appearance')),'Tuner unavailable');
 const tuner=application.windows().find(w=>w.url().includes('role=appearance'));
 tuner.on('pageerror',error=>result.errors.push(error.message));
 await tuner.waitForSelector('.material-tuner');
 await tuner.evaluate(async()=>{await window.appearance.tune({blurSigma:1.2});await window.appearance.configure({motion:{pull:18},reduced:true});await window.appearance.saveMaterial();await window.appearance.saveMotion();});
 const saved=await tuner.evaluate(()=>window.appearance.config()); assert.equal(saved.saved.material.dirty,false); assert.equal(saved.saved.motion.dirty,false);check('live tuning and independent saves');
 await tuner.getByRole('button',{name:'恢复候选24验收预设（先预览）',exact:true}).click();
 await waitFor(async()=> (await tuner.evaluate(()=>window.appearance.config())).saved.material.dirty,'Preset did not mark preview dirty');check('accepted default is preview only');
 await tuner.evaluate(()=>window.appearance.restoreSaved('material')); assert.equal((await tuner.evaluate(()=>window.appearance.config())).material.blurSigma,1.2);check('restore saved values is separate from defaults');
 await tuner.getByRole('button',{name:'恢复候选24验收预设（先预览）',exact:true}).click();
 await getMain("main.windows.get('appearance').close()"); assert.equal(await getMain("main.windows.get('orb').isVisible()"),true);check('closing tuner preserves demo');
 await getMain("main.act('toggle-material')");
 await waitFor(async()=> (await telemetry())?.liveTracks===0,'Tracks not released on off');check('material off releases capture');
 await getMain("main.act('toggle-material')"); await waitFor(async()=> (await telemetry())?.liveTracks>0,'Restart failed');
 await getMain("main.act('hide')"); await waitFor(async()=> (await telemetry())?.liveTracks===0,'Tracks not released on hide');check('hide releases capture');
 await getMain("main.act('show')"); await waitFor(async()=> (await telemetry())?.liveTracks>0,'Show failed');check('show reacquires real capture');
 await getMain("main.windows.get('orb').webContents.send('appearance:diagnostic','lose-context')");
 await waitFor(async()=> (await telemetry())?.liveTracks===0,'Context loss did not release');check('context loss releases and degrades');
 await getMain("main.act('toggle-material')"); await waitFor(async()=> (await telemetry())?.liveTracks>0,'Context recovery failed');check('explicit restart after context loss');
 await application.close();application=await launch(); await getMain('main.ready');
 const restored=await getMain('main.appearance.config()');assert.equal(restored.material.blurSigma,1.2);assert.equal(restored.motion.pull,18);assert.equal(restored.reduced,true);check('restart restores saved values, discards unsaved preset');
 await application.close();application=undefined;check('application exits');
 assert.equal(result.errors.length,0);result.ok=true;
} catch(error){result.errors.push(error.stack ?? String(error));console.error(error);process.exitCode=1;}
finally {if(application)await application.close().catch(()=>{});if(fixture)await fixture.close().catch(()=>{});await writeFile(path.join(run,'result.json'),JSON.stringify(result,null,2));console.log('Desktop evidence: '+run);}
